# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LBFM-Swift' do
  use_frameworks!

  # Pods for LBFM-Swift
  pod 'SnapKit'
  pod 'Kingfisher'
  #tabbar样式
  pod 'ESTabBarController-swift'
  #banner滚动图片
  pod 'FSPagerView'
  pod 'Moya'
  pod 'HandyJSON', '~> 4.2.0'
  pod 'SwiftyJSON'
  # 分页
  pod 'DNSPageView'
  #跑马灯
  pod 'JXMarqueeView'
  #滚动页
  pod 'LTScrollView'
  pod 'MJRefresh'
  #pod 'SkeletonView'
  #消息提示
  pod 'SwiftMessages'
  #pod 'YYKit'
  pod 'SVProgressHUD'
  #播放网络音频
  pod 'StreamingKit'
end
